version: '3.8'
services:
  ffmpeg-nginx:
    image: public.ecr.aws/w2o0b9g0/frillweeman/brewcast-prod:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - SSL_CERTIFICATE=/etc/letsencrypt/live/dunkinradio.org/fullchain.pem
      - SSL_CERTIFICATE_KEY=/etc/letsencrypt/live/dunkinradio.org/privkey.pem
    restart: always

  certbot:
    image: certbot/certbot
    environment:
      - CERTBOT_EMAIL
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    command: certonly --webroot -w /var/www/certbot -d dunkinradio.org --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email
